language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab3-stackanqueue
  - make -j
  - ./test/test_TSteck
notifications:
  email: false
